aguo/ruki/config/routes.rb
Wiki::Application.routes.draw do
  base_url = Wiki::Application.config.root_path
  scope base_url do
    root :to => 'wiki#index'

    resources :projects do
      collection do
        get 'index'
        get 'login'
        post 'login'
        get 'lang'
      end
      resources :wiki do
        member do
          get 'add'
          get 'page'
          get 'edit'
          post 'edit'
          get 'revisions'
          get 'diff'
          match 'revisions/:rid' => 'wiki#revision_page'
          post 'preview'
        end
        collection do
          get 'index'
          get 'list'
          post 'list'
          get 'help'
          post 'web_upload'
          get 'files'
          post 'delete_files'
        end
      end
    end
  end

end

aguo/ruki/app/models/projects.rb
class Projects < ActiveRecord::Base
end

aguo/ruki/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Projects.all
  end

  def login
    if request.post?
      if params[:submit_wangaguo]
        session["login_name"] = "wangaguo"
      elsif params[:submit_shawn]
        session["login_name"] = "shawn"
      else
        session["login_name"] = "guest"
      end
      redirect_to projects_path
    end
  end

  def lang
    if params[:lang] == 'en'
      session["wiki_lang"] = 'en'
    else
      session["wiki_lang"] = 'zh_TW'
    end
    redirect_to projects_path 
  end
end

aguo/ruki/app/views/projects/index.html.erb
<hr/>
Project wiki list: 
<ul>
<% @projects.each do |p| %>
  <%= link_to p.name, project_wiki_index_path(p.id)%><br/>
<% end %>
</ul>

aguo/ruki/app/views/projects/login.html.erb
<%= form_tag :action => "login" do %>
  <%= submit_tag "Login as guest", :name => "submit_guest" %>
  <%= submit_tag "Login as wangaguo", :name => "submit_wangaguo" %>
  <%= submit_tag "Login as shawn", :name => "submit_shawn" %>
<% end %>
<ul>
  <li>wangaguo is project member and has permission.</li>
  <li>shawn is project member and no permission.</li>
</ul>