aguo/ruki/config/routes.rb
Wiki::Application.routes.draw do
  base_url = Wiki::Application.config.root_path
  scope base_url do
    root :to => 'wiki#index'

    resources :projects do
      collection do
        get 'index'
        get 'login'
        post 'login'
        get 'lang'
      end
      resources :wiki do
        member do
          get 'add'
          get 'page'
          get 'edit'
          post 'edit'
          get 'revisions'
          get 'diff'
          match 'revisions/:rid' => 'wiki#revision_page'
          post 'preview'
        end
        collection do
          get 'index'
          get 'list'
          post 'list'
          get 'help'
          post 'web_upload'
          get 'files'
          post 'delete_files'
        end
      end
    end
  end

end

aguo/ruki/app/controllers/wiki_controller.rb
require 'zip/zip'
require 'net/http'
require 'fileutils'

class WikiController < ApplicationController
  #require 'RMagick'
  #include Magick
  #layout 'wiki'
  include ActionView::Helpers::NumberHelper
  before_filter :timezone
  before_filter :check_permission

  def timezone
    Time.zone = 8 
    I18n.locale = session['wiki_lang'] || "zh_TW"
    @wiki_permit = fpermit?("wiki", params[:project_id])
    @project = Projects.find_by_id(params[:project_id])
    if @project.nil?
      flash[:warning] = "project is not exists."
      redirect_to :controller => :projects
      return
    end
  end

  def index
    redirect_to :action => :show, :id => 'HomePage' 
  end

  def show
    page
  end

  #show wiki page content
  def page
    unless params[:id].nil?
      @wiki_page = WikiPages.page_all.find_by_project_id_and_name(params[:project_id], params[:id])
      if @wiki_page
        #Is private page
        if @wiki_permit == false and @wiki_page.status == WikiPages::STATUS[:PRIVATE]
          flash[:warning] = t("is private page", :name => @wiki_page.name, :scope => 'wiki.message')
          redirect_to :action => 'list'
          return
        end
        #show revision page
        unless params[:r].nil?
          @revision = WikiRevisions.find_by_page_id_and_revision(@wiki_page.id, params[:r])
          @wiki_page.content = @revision.content unless @revision.nil?
        end
        parser = Wikitext::Parser.new
        parser.internal_link_prefix = "#{project_wiki_index_path}/"
        parser.img_prefix = "#{root_path}/wiki_upload/#{params[:project_id]}/"
        @wiki_html = parser.parse(@wiki_page.content)
      elsif @wiki_permit #No HomePage and has permit
        redirect_to :action => 'edit'
        return
      else #No HomePage and no permit
        @wiki_page = WikiPages.new
        @wiki_page.name = "HomePage"
        @wiki_html = t("This page is no content", :scope => 'wiki.message') + "<br/></br/></br>"
      end
      render :template => 'wiki/page'
    end
  end

  #will remove?
  #def revision_page
  #  unless params[:rid].nil?
  #    @wiki_page = WikiPages.find_by_name(params[:id])
  #    @revision = WikiRevisions.find_by_page_id_and_revision(@wiki_page.id, params[:rid])
  #    parser = Wikitext::Parser.new
  #    parser.internal_link_prefix = "#{project_wiki_index_path}/"
  #    @wiki_html = parser.parse(@revision.content)
  #    render :template => 'wiki/page'
  #  end
  #end

  def list
    if request.post? and !params[:page_id].nil? and @wiki_permit
      if params[:submit_delete] or params[:submit_protected] or 
         params[:submit_private] or params[:submit_public]
        ActiveRecord::Base.transaction do
          params[:page_id].each do |pid|
            wp = WikiPages.page_all.where(:project_id => params[:project_id]).where(:id => pid)
            if wp[0]
              if params[:submit_delete]
                wp[0].status = WikiPages::STATUS[:DELETED] 
              elsif params[:submit_protected]
                wp[0].status = WikiPages::STATUS[:PROTECTED] 
              elsif params[:submit_private]
                wp[0].status = WikiPages::STATUS[:PRIVATE] 
              elsif params[:submit_public]
                wp[0].status = WikiPages::STATUS[:PUBLIC] 
              end
              if wp[0].name == 'HomePage' and params[:submit_private]
                flash.now[:warning] = "頁面 HomePage 不能設為私有頁面"
              else
                wp[0].save
              end
            end
          end
        end
      elsif params[:submit_export_html]
        export_html
      elsif params[:submit_export_pdf]
        export_pdf
      elsif params[:submit_export_wiki]
        export_wiki
      end
    end

    if @wiki_permit
      @wiki_pages = WikiPages.page_all.where(:project_id => params[:project_id])
    else
      @wiki_pages = WikiPages.page_guest.where(:project_id => params[:project_id])
    end
    
    if params[:search]
      @wiki_pages = @wiki_pages.where("(name like '%#{params[:search]}%' " + 
                                      "or summary like '%#{params[:search]}%' " +
                                      "or content like '%#{params[:search]}%')")
    end
    @search = params[:search]
  end

  def edit
    ActionView::Base.send(:include, Recaptcha::ClientHelper)
    ActionController::Base.send(:include, Recaptcha::Verify)

    @wiki_page = WikiPages.page_all.find_by_project_id_and_name(params[:project_id], params[:id])
    if @wiki_page.nil? #page not exists.
      unless @wiki_permit
        flash[:warning] = t("No Permission", :scope => 'wiki.message')
        redirect_to :action => 'list'
        return
      end
      @wiki_page = WikiPages.new
      @wiki_page.name = params[:id]
      @wiki_page.status = WikiPages::STATUS[:PROTECTED]
    elsif @wiki_permit == false and @wiki_page.status != WikiPages::STATUS[:PUBLIC]
      flash[:warning] = t("No Permission", :scope => 'wiki.message')
      redirect_to :action => 'list'
      return
    end

    wp = @wiki_page
    if request.post? 
      wp.name = params[:wiki_page][:name]
      wp.summary = params[:wiki_page][:summary]
      wp.content = params[:wiki_page][:content]
      wp.log = params[:wiki_page][:log]
      if params[:submit_preview]
        parser = Wikitext::Parser.new
        parser.internal_link_prefix = "#{project_wiki_index_path}/"
        parser.img_prefix = "#{root_path}/wiki_upload/#{params[:project_id]}/"
        @wiki_html = parser.parse(wp.content)
      else params[:submit_save]
        err_msg = ''
        if params[:wiki_page][:name] == 'NoName'
          err_msg += t('Please input a new page name', :scope => 'wiki.message') + '</br>'
        end
        if params[:wiki_page][:content].strip == ""
          err_msg += t('Please input content', :scope => 'wiki.message') + '</br>'
        end
        if params[:wiki_page][:name].strip == ""
          err_msg += t('Please input page name', :scope => 'wiki.message') + '</br>'
        end
        unless WikiPages.page_all.
                 where(:project_id => params[:project_id]).
                 where(:name => params[:wiki_page][:name]).
                 where("id <> '#{wp.id}'").empty? 
          err_msg += t('Page name already exist', :scope => 'wiki.message') + '</br>'
        end
        if err_msg != ""
          flash.now[:warning] = err_msg.html_safe
          return
        end
        if current_user.login == 'guest' and verify_recaptcha == false
          flash.now[:warning] = t('Please confirm captcha', :scope => 'wiki.message') 
          return
        end

        wp.project_id = params[:project_id]
        if params[:is_revision] == '1'
          wp.revision = (wp.revision || 0) + 1
        else
          wp.revision = (wp.revision || 0)
        end
        wp.revised_at = Time.now
        wp.revised_by = current_user.login 
        wp.save

        if params[:is_revision] == '1'
          wr = WikiRevisions.new
          wr.page_id = wp.id
          wr.content = wp.content
          wr.log = wp.log
          wr.revision = wp.revision
          wr.revised_at = wp.revised_at
          wr.revised_by = wp.revised_by
          wr.save
        end
        redirect_to :id => params[:wiki_page][:name] || wp.name, :action => 'show'
      end
    else
      @wiki_page.log = ""
    end
  end

  def revisions
    @wiki_page = WikiPages.find_by_name(params[:id])
    @revisions = WikiRevisions.where(:page_id => @wiki_page.try(:id)).order("revision desc")
  end

  def diff
    pid = params[:id]
    @wiki_page = WikiPages.page_all.find_by_name(pid) 
    if params[:r1]
      @r1 = WikiRevisions.find_by_page_id_and_revision(@wiki_page.id, params[:r1])
    end
    if @r1.nil?
      @r1 = @wiki_page
    end
    if params[:r2]
      @r2 = WikiRevisions.find_by_page_id_and_revision(@wiki_page.id, params[:r2])
    end
    Diffy::Diff.default_format = :html
    @diff_html = Diffy::Diff.new(@r2.content, @r1.content)
  end

  def files
    path = File.join(WIKI_UPLOAD_PATH, '/', params[:project_id], "/*")
    @files = [];
    Dir.glob(path){ |file|
      unless File.directory?(file)
        file_row = {} 
        file_row[:name] = File.basename(file)
        File.open(file, "rb") do |f|
           img = ImageSize.new(f)
           file_row[:format] = img.format
           file_row[:size] = f.stat.size
           file_row[:mtime] = f.stat.mtime
           file_row[:imagesize] = "#{img.w} * #{img.h}" unless img.w.nil?
           file_row[:path] = file
        end
        @files << file_row 
      end
    }
  end

  def delete_files
    unless params[:files].nil?
      params[:files].each do |f|
        begin 
          File.delete(File.join(WIKI_UPLOAD_PATH, params[:project_id], f))
          File.delete(File.join(WIKI_UPLOAD_PATH, params[:project_id], 'small', f))
        rescue 
        end
      end
    end
    redirect_to :action => 'files'
  end

  def web_upload
    if !params[:upload_file].nil?
      #Check and create folder
      project_path = File.join(WIKI_UPLOAD_PATH, params[:project_id])
      unless File.directory?(project_path)
        Dir.mkdir(project_path)
        Dir.mkdir(File.join(project_path, 'small'))
      end
      Dir.chdir(project_path)

      #Upload each file with check exists and size. 
      file_exists = []
      file_size_check = true 
      file_size_total = 0
      params[:upload_file].each do |f|
        file_size_total += f.size
        if f.size > 6*1024*1024#WIKI_MAX_UPLOAD_FILE_SIZE
          file_size_check = false
        end
        if File.exists?(f.original_filename)
          file_exists << f.original_filename
        end
      end

      #Check file size & total size
      foder_size = %x[du -s #{project_path}].scan(/^\d*/)[0].to_i
      if file_size_check == false
        flash[:warning] = t("File size limit ") + number_to_human_size(WIKI_MAX_UPLOAD_FILE_SIZE)
      elsif ((file_size_total+foder_size) > 2*1024*1024)#WIKI_MAX_UPLOAD_TOTAL_SIZE)
        flash[:warning] = t("Total file size limit", 

aguo/ruki/app/helpers/wiki_helper.rb
module WikiHelper
end

aguo/ruki/app/views/wiki/_functions.html.erb
<div id="wiki_functions">
  <a href="<%= project_wiki_path(params[:project_id], 'HomePage') %>"><%= t("Home", :scope => :wiki) %></a> |
  <a href="<%= list_project_wiki_index_path %>"><%= t("List", :scope => :wiki) %></a> |
  <% if @wiki_permit == true %>
    <a href="<%= edit_project_wiki_path(params[:project_id], 'NoName') %>"><%= t("New", :scope => :wiki) %></a> |
  <% end %>
  <% if !params[:id].nil? and (@wiki_permit or @wiki_page.status == WikiPages::STATUS[:PUBLIC]) -%>
    <a href="<%= edit_project_wiki_path(params[:project_id], params[:id]) %>"><%= t("Edit", :scope => :wiki) %></a> |
  <% end -%>
  <% if !params[:id].nil? and @wiki_permit == true -%>
    <a href="<%= revisions_project_wiki_path %>"><%= t("Revisions", :scope => :wiki) %></a> |
  <% end -%>
  <% if @wiki_permit == true -%>
    <a href="<%= files_project_wiki_index_path %>"><%= t("Files", :scope => :wiki) %></a> |
  <% end -%>
  <a href="<%= help_project_wiki_index_path %>"><%= t("Help", :scope => :wiki) %></a> |
  <%= form_tag({:action => "list"}, {:style => "margin:0;padding:0;display:inline;"}) do %>
    <%= text_field_tag :search, @search %>
  <% end %>
</div>

aguo/ruki/app/views/wiki/diff.html.erb
<h2><%= @wiki_page.name %> <%= t('Diff', :scope => :wiki) %></h2>

<%= render :partial => "functions"%>
<hr/>
<%= t('Diff', :scope => :wiki) %>: 
<% if @r1.class.to_s == 'WikiPages' %>
  <%= t('Current Page', :scope => :wiki) %>
<% else %>
  r<%= @r1.revision %>
<% end %>
<%= t('and', :scope => :wiki) %> r<%= @r2.revision %>
<br/><br/>
<%= @diff_html.to_s.html_safe %>
<hr/>
<%= render :partial => "functions"%>

aguo/ruki/app/views/wiki/edit.html.erb
<h2>
  <%= @wiki_page.name %>
  <% if params[:wiki_page].nil? || params[:submit_preview]-%>
  <% else -%>
    <%#= @wiki_page.name -%>
  <% end %>
</h2>
<%= render :partial => "functions"%>
<hr/>

<%= form_tag :action => 'edit' do %>
  <% if @wiki_html %>
    <%= @wiki_html.html_safe %>
  <% end %>
  <%= t('Page Name', :scope => :wiki) %>: <%= text_field(:wiki_page, :name) %> 
  <br/>
  <%= t('Summary', :scope => :wiki) %>:
  <%= text_field :wiki_page, :summary, :size => 80 %>
  <br/>
  <%= text_area :wiki_page, :content, :cols => 80, :rows => 20  %>
  <br/>
  <%= t('Commit log', :scope => :wiki) %>:
  <br/>
  <%= text_area :wiki_page, :log, :cols => 80, :rows => 5  %>
  <br/>
  <% if current_user.login == 'guest' %>
    <%= recaptcha_tags %> 
  <% end %>
  <%= submit_tag t('Preview', :scope => :wiki), :name => 'submit_preview' %>
  <%= submit_tag t('Save', :scope => :wiki), :name => 'submit_save' %>
  <% if @wiki_permit %>
    <%= check_box_tag 'is_revision' %><%= t('Need be a revision', :scope => :wiki) %>
  <% else %>
    <%= hidden_field_tag 'is_revision', '1' %>
  <% end %>
<% end %>

<hr/>
<%= render :partial => "functions"%>

aguo/ruki/app/views/wiki/export.html.erb
<h2>WikiPageName</h2>

<%= render :partial => "functions"%>
<hr/>
<pre>


這是Export頁面


</pre>
<hr/>
<%= render :partial => "functions"%>

aguo/ruki/app/views/wiki/files.html.erb
<% content_for :page_head do %>
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.6/jquery.min.js"></script>
  <link rel="stylesheet" href="http://tablesorter.com/themes/blue/style.css" />
  <script type="text/javascript" src="http://autobahn.tablesorter.com/jquery.tablesorter.min.js"></script>
  <script type="text/javascript" src="http://tablesorter.com/addons/pager/jquery.tablesorter.pager.js"></script>
  <script type="text/javascript" src="/of/yoxview/yoxview-init.js"></script>
<% end %>
<% content_for :ujs do %>
  $.noConflict();
  var pp = 0;
  (function($){
    $(document).ready(function() {
      $("#wiki_list_check_box_all").click(function(){
        if($(this).attr('checked') == 'checked')
        {
          jQuery.each($('[name="files[]"]'), function() {
            $(this).attr('checked', 'checked');
          });
        }
        else
        {
          jQuery.each($('[name="files[]"]'), function() {
            $(this).removeAttr('checked');
          });
        }
      });

      $(":submit[name='delete']").click(function(){
        if($(':checkbox[name="files[]"]:checked').length == 0){
        alert('<%= t('No selected items', :scope => [:wiki, :message]) %>');
          return false;
        }
      });

      $("table")
        .tablesorter({widthFixed:true, widgets:['zebra'], headers:{0:{sorter:false}, 5:{sorter:false}}})
        .tablesorterPager({container: $("#pager"), size:10, positionFixed:false});
      $(".yoxview").yoxview();
    });
  })(jQuery);
<% end %>

<h2><%= t('Files List', :scope => :wiki) %></h2>

<%= render :partial => "functions" %>
<hr/>

<%= t('Upload files', :scope => :wiki) %>:
<%= form_tag({:action => 'web_upload'}, :multipart => true) do %>
  <%# form_tag ({:project_id => @project.id, :id => @release.id, :action => 'web_upload'}, :multipart => true) do %>
  <% for i in 1..3 %>
    <%= file_field_tag("upload_file[]") %><br/>
  <% end %>
  <%= submit_tag t('Upload', :scope => :wiki) %>
  <%= submit_tag t('Reset', :scope => :wiki), :type => 'reset' %> 
<% end %>

<%= form_tag({:action => 'delete_files'}) do %>
  </div>
  <table class="tablesorter yoxview">
    <thead>
      <th style="width:15px"><input type="checkbox" id="wiki_list_check_box_all"></th>
      <th><%= t('File Name', :scope => :wiki) %></th>
      <th><%= t('File Size', :scope => :wiki) %></th>
      <th><%= t('Upload Date', :scope => :wiki) %></th>
      <th><%= t('Image Size', :scope => :wiki) %></th>
      <th><%= t('Image Preview', :scope => :wiki) %></th>
    </thead>
  <% @files.each do |f| -%>
    <tr>
      <td><%= check_box_tag "files[]", f[:name] %></td>
      <td><%= f[:name] %></td>
      <td><%= number_to_human_size(f[:size]) %></td>
      <td><%= tz_datetime(f[:mtime]) %></td>
      <td><%= f[:imagesize] %></td>
      <td>
        <% if f[:name].to_s =~ /\.(jpg|jpeg|gif|bmp|png|ico)$/ -%>
          <a href="<%= "/of/wiki_upload/#{params[:project_id]}/#{f[:name]}" %>">
            <img src="<%= "/of/wiki_upload/#{params[:project_id]}/small/#{f[:name]}" %>" />
          </a>
        <% end -%> 
      </td>
    </tr>
  <% end -%>
  </table>
  <%= render :partial => "pager" %>
  <%= submit_tag t('Delete', :scope => :wiki), :name => 'delete', :confirm => t('Are you sure?', :scope => [:wiki, :message]) %>
<% end %>

<hr/>
<%= render :partial => "functions" %>

aguo/ruki/app/views/wiki/list.html.erb
<% content_for :page_head do %>
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.6/jquery.min.js"></script> 
  <link rel="stylesheet" href="http://tablesorter.com/themes/blue/style.css" />
  <script type="text/javascript" src="http://autobahn.tablesorter.com/jquery.tablesorter.min.js"></script>
  <script type="text/javascript" src="http://tablesorter.com/addons/pager/jquery.tablesorter.pager.js"></script>
<% end %>
<% content_for :ujs do %>
  $.noConflict();
  (function($){
    $(document).ready(function(){
      $("#wiki_list_check_box_all").click(function(){
        if($(this).attr('checked') == 'checked')
        {
          jQuery.each($('[name="page_id[]"]'), function() {
            $(this).attr('checked', 'checked');
          });
        }
        else
        {
          jQuery.each($('[name="page_id[]"]'), function() {
            $(this).removeAttr('checked');
          });
        }
      });

      $(":submit").click(function(){
        if($(':checkbox[name="page_id[]"]:checked').length == 0){
        alert('<%= t('No selected items.', :scope => [:wiki, :message]) %>');
          return false;
        }
      });
  
      $("table") 
        .tablesorter({widthFixed: true, widgets: ['zebra'], headers:{0:{sorter:false}}})
        .tablesorterPager({container: $("#pager"), size:10, positionFixed:false}); 
    });
  })(jQuery);
<% end %>

<h2><%= t('Pages List', :scope => :wiki) %></h2>

<%= render :partial => "functions"%>
<hr/>

<%= form_tag :action => 'list' do %>
  <% if @wiki_permit -%>
    <%= submit_tag "#{t('Export', :scope => :wiki)} Wiki", :name => 'submit_export_wiki' %>
    <%= submit_tag "#{t('Export', :scope => :wiki)} HTML", :name => 'submit_export_html' %>
    <%#= submit_tag "#{t('Export')} PDF", :name => 'submit_export_pdf' %>
    <%= submit_tag t('Protected', :scope => :wiki), :name => 'submit_protected' %>
    <%= submit_tag t('Private', :scope => :wiki), :name => 'submit_private' %>
    <%= submit_tag t('Public', :scope => :wiki), :name => 'submit_public' %>
    <%= submit_tag t('Delete', :scope => :wiki), :name => 'submit_delete', 
                   :confirm => t('Are you sure?', :scope => [:wiki, :message]) %>
  <% end -%>
  <table class="tablesorter">
  <thead>
    <th style="width:15px"><input type="checkbox" id="wiki_list_check_box_all"></th>
    <th><%= t('Page Name', :scope => :wiki) %></th>
    <th><%= t('Summary', :scope => :wiki) %></th>
    <th><%= t('Author', :scope => :wiki) %></th>
    <th><%= t('Revision', :scope => :wiki) %></th>
    <th><%= t('Status', :scope => :wiki) %></th>
    <th><%= t('Modify Time', :scope => :wiki) %></th>
  </thead>
  <% @wiki_pages.each do |wiki_page|-%>
  <tr>
    <td><%= check_box_tag "page_id[]", wiki_page.id %></td>
    <td><%= link_to wiki_page.name, project_wiki_path(params[:project_id], wiki_page.name) %></td>
    <td><%= wiki_page.summary %></td>
    <td><%= wiki_page.revised_by %></td>
    <td><%= wiki_page.revision %></td>
    <td><%= t(wiki_page.status_to_s, :scope => :wiki) %></td>
    <td><%= tz_datetime(wiki_page.revised_at) %></td>
  </tr>
  <% end -%>
  </table>
  <%= render :partial => "pager" %>
<% end %>

<hr/>
<%= render :partial => "functions"%>

aguo/ruki/app/views/wiki/new.html.erb
<h2>WikiPageName</h2>

<%= render :partial => "functions"%>
<hr/>

<% if @wiki_html %>
  <%= @wiki_html.html_safe %>
<% end %>
<%= form_tag '/of' do %>
<%= text_area :wiki_page, :content, :cols => 80, :rows => 20  %>
<%= submit_tag 'Preview' %>
<% end %>

<hr/>
<%= render :partial => "functions"%>

aguo/ruki/app/views/wiki/page.html.erb
<h2>
  <%= @wiki_page.name %> 
  <% if params[:r] -%> 
    - revision <%= params[:r] %>
  <% end -%>
</h2>

<%= render :partial => "functions" %>
<hr/>
<em><%= @wiki_page.summary %></em>
<% if params[:r] and @revision.nil? -%>
  <%= t('This revision is not exists', :scope => [:wiki, :message]) %>
<% else -%>
  <% if @wiki_html -%>
     <%= @wiki_html.html_safe %>
     <% if @wiki_page.revised_by %>
       <%= "#{t('Updated', :scope => :wiki)} #{@wiki_page.revised_at} by #{@wiki_page.revised_by}" %>
     <% end %>
  <% end -%>
  <% if @revision -%>
    <br/>
 <textarea cols="80" rows="10">
 <%= @revision.content %>
 </textarea>
  <% end -%>
<% end %>
<hr/>
<%= render :partial => "functions" %>

aguo/ruki/app/views/wiki/revisions.html.erb
<% content_for :page_head do %>
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.6/jquery.min.js"></script>
  <link rel="stylesheet" href="http://tablesorter.com/themes/blue/style.css" />
  <script type="text/javascript" src="http://autobahn.tablesorter.com/jquery.tablesorter.min.js"></script>
  <script type="text/javascript" src="http://tablesorter.com/addons/pager/jquery.tablesorter.pager.js"></script>
<% end %>
<% content_for :ujs do %>
  $.noConflict();
  (function($){
    $(document).ready(function(){
      $("table")
        .tablesorter({widthFixed: true, widgets: ['zebra'], headers:{0:{sorter:false}}})
        .tablesorterPager({container: $("#pager"), size:10, positionFixed:false});
    });
  })(jQuery);
<% end %>


<h2><%= params[:id] %> <%= t('Revisions', :scope => :wiki) %></h2>

<%= render :partial => "functions"%>
<hr/>
<% if @revisions.empty? %>
  <%= t('This page is not exists', :scope => [:wiki, :message]) %>
<% else %>
  <table class="tablesorter">
    <thead>
      <th><%= t('Revision', :scope => :wiki) %></th>
      <th><%= t('Diff with current', :scope => :wiki) %></th>
      <th><%= t('Log', :scope => :wiki) %></th>
      <th><%= t('Revised by', :scope => :wiki) %></th>
      <th><%= t('Revised Date', :scope => :wiki) %></th>
    </thead>
  <% @revisions.each do |r| -%>
    <tr align="center">
      <td><a href="./?r=<%=r.revision%>">r<%= r.revision %></a></td>
      <td><a href="diff?r2=<%=r.revision%>"><%= t('Diff', :scope => :wiki) %></a></td>
      <td><%= r.log %></td>
      <td><%= r.revised_by %></td>
      <td><%= r.revised_at %></td>
    </tr>
  <% end -%>
  </table>
  <%= render :partial => "pager" %>
<% end %>
<hr/>
<%= render :partial => "functions"%>