aguo/ruki/config/routes.rb
Wiki::Application.routes.draw do
  base_url = Wiki::Application.config.root_path
  scope base_url do
    root :to => 'wiki#index'

    resources :projects do
      collection do
        get 'index'
        get 'login'
        post 'login'
        get 'lang'
      end
      resources :wiki do
        member do
          get 'add'
          get 'page'
          get 'edit'
          post 'edit'
          get 'revisions'
          get 'diff'
          match 'revisions/:rid' => 'wiki#revision_page'
          post 'preview'
        end
        collection do
          get 'index'
          get 'list'
          post 'list'
          get 'help'
          post 'web_upload'
          get 'files'
          post 'delete_files'
        end
      end
    end
  end

end

aguo/ruki/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wiki</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <%= yield :page_head %>
  <script type="text/javascript">
    <%= yield :ujs %>
  </script>
</head>
<body>
  <%= link_to 'Wiki List', projects_path() %> |
  <%= link_to 'login', :action => :login, :controller => :projects %> |
  <% if session['wiki_lang'] == 'en' %>
    <%= link_to 'Chinese', :action => :lang, :controller => :projects, :lang => 'tw' %>
  <% else %>
    <%= link_to 'English', :action => :lang, :controller => :projects, :lang => 'en' %>
  <% end %>
  <br/>
  current_user is <%= current_user.login%><br/>
  <span style="color:red"><%= flash[:warning] %></span>
  <%= yield %>
</body>
</html>